### ISSUE TITLE
[Enhancement/Request] Use [go-appimage](https://github.com/probonopd/go-appimage)'s "self contained" mode to provide a version of this appimage that works on Musl-based systems and other minimal ones. :)

### ISSUE THREAD

**Issue by xplshn** [Samueru-sama/mpv-AppImage#1]

**Comment by Samueru-sama** [comment]
Yes, I actually want to remove the other appimage and just have the anylinux one, but this issue is holding me: https://github.com/probonopd/go-appimage/issues/298

Btw your older profile pic was perfect, what happened? 😭

**Comment by xplshn** [comment]
> Yes, I actually want to remove the other appimage and just have the anylinux one, but this issue is holding me: https://github.com/probonopd/go-appimage/issues/298

Oh, strange bug

BTW, I noticed that you're using static compilations of some binaries inside of some of your appimages, consider using the binaries from `dbin`, since they're all statically linked, and the majority of them get compiled in Musl environments, which makes them both compliant and smaller.

> Btw your older profile pic was perfect, what happened? 😭

I watched Lain Serial Experiments 😭 (i shouldn't have, the ending is just too sad)

**Comment by xplshn** [comment]
I hope we can collaborate some time, my dream is to build a fairly small system like Oasis Linux, that is both simple enough to rebuild with a few deps, and has only statically linked binaries. Not even an ld.so shall be shipped. I'd also really like to have a filesystem like Gobo's, but with:
```
/system/bin
/system/share
/system/rescue/bin (instead of sbin)
/user
/programs
```

I've actually made a lot of progress on this with `dbin`, you can get a rootfs from https://landley.net/toybox/downloads/binaries/mkroot/latest and add `dbin` to it, set up a few things, change the init file and a few quick edits to /etc to get a fairly okay system. What I can't figure out tho is how to boot it, but working from a chroot, everything works.

**Comment by Samueru-sama** [comment]
> BTW, I noticed that you're using static compilations of some binaries inside of some of your appimages, consider using the binaries from `dbin`, since they're all statically linked, and the majority of them get compiled in Musl environments, which makes them both compliant and smaller.

Note taken, this mpv appimage is made with the MPV build scripts which is the recommended way for building mpv.

I recently had to build the vulkan headers as well since they upped the requirement.
